module.exports = {
    petlove: 'Petlove',

    deal: [
        {
            suffix: 'deals',
            path: 'content/images/bat-dog-toy.png',
            desc: 'bat dog toy',
            price: 1.99,
            discount: true,
            discountAmount: 20,
        },
        {
            suffix: 'deals',
            path: 'content/images/dog-food.png',
            desc: 'savory wet dog food',
            price: 4.99,
            discount: true,
            discountAmount: 20,
        },
        {
            suffix: 'deals',
            path: 'content/images/cat-tunnel.png',
            desc: 'cat tunnel',
            price: 10.99,
            discount: true,
            discountAmount: 20,
        },
        {
            suffix: 'deals',
            path: 'content/images/ewok-hallowen-costume.png',
            desc: 'ewok hallowen costume',
            price: 15.99,
            discount: true,
            discountAmount: 20,
        },
        {
            suffix: 'deals',
            path: 'content/images/batman-hallowen-costume.png',
            desc: 'batman costume',
            price: 15.99,
            discount: true,
            discountAmount: 20,
        },
        {
            suffix: 'deals',
            path: 'content/images/superman-hallowen-costume.png',
            desc: 'superman costume',
            price: 10.99,
            discount: true,
            discountAmount: 20,
        },
    ],
    pet: [
        {
            suffix: 'pets',
            path: 'content/images/elephant-costume.png',
            desc: 'elepahnt costume',
            price: 16.9,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/super-girl-costume.png',
            desc: 'supergirl costume',
            price: 10.99,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/wonder-woman-costume.png',
            desc: 'wonder woman costume',
            price: 12.99,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/super-rat-costume.png',
            desc: 'super rat costume',
            price: 9.99,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/witch-costume.png',
            desc: 'witch costume',
            price: 9.99,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/dragon-costume.png',
            desc: 'dragon costume',
            price: 16.99,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/marmaid-costume.png',
            desc: 'mermaid costume',
            price: 12.99,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/tortilla-costume.png',
            desc: 'tortilla costume',
            price: 18.99,
            discount: false,
        },
        {
            suffix: 'pets',
            path: 'content/images/prisioner-costume.png',
            desc: 'prisoner costume',
            price: 10.99,
            discount: false,
        },
    ],
}
