export const data = [
    {
        id: '1',
        suffix: 'deals',
        path: 'content/images/bat-dog-toy.png',
        width: '350',
        height: '370',
        desc: 'bat dog toy',
        price: 1.99,
        discount: true,
        discountAmount: 20,
    },
    {
        id: '2',
        suffix: 'deals',
        path: 'content/images/dog-food.png',
        width: '350',
        height: '370',
        desc: 'savory wet dog food',
        price: 4.99,
        discount: true,
        discountAmount: 20,
    },
    {
        id: '3',
        suffix: 'deals',
        path: 'content/images/cat-tunnel.png',
        width: '350',
        height: '370',
        desc: 'cat tunnel',
        price: 10.99,
        discount: true,
        discountAmount: 20,
    },
    {
        id: '4',
        suffix: 'deals',
        path: 'content/images/ewok-hallowen-costume.png',
        width: '350',
        height: '370',
        desc: 'ewok hallowen costume',
        price: 15.99,
        discount: true,
        discountAmount: 20,
    },
    {
        id: '5',
        suffix: 'deals',
        path: 'content/images/batman-hallowen-costume.png',
        width: '350',
        height: '370',
        desc: 'batman costume',
        price: 15.99,
        discount: true,
        discountAmount: 20,
    },
    {
        id: '6',
        suffix: 'deals',
        path: 'content/images/superman-hallowen-costume.png',
        width: '350',
        height: '370',
        desc: 'superman costume',
        price: 10.99,
        discount: true,
        discountAmount: 20,
    },
    {
        id: '7',
        suffix: 'pets',
        path: 'content/images/elephant-costume.png',
        width: '262',
        height: '276',
        desc: 'elephant costume',
        price: 16.99,
        discount: false,
    },
    {
        id: '8',
        suffix: 'pets',
        path: 'content/images/super-girl-costume.png',
        width: '262',
        height: '276',
        desc: 'supergirl costume',
        price: 10.99,
        discount: false,
    },
    {
        id: '9',
        suffix: 'pets',
        path: 'content/images/wonder-woman-costume.png',
        width: '262',
        height: '276',
        desc: 'wonder woman costume',
        price: 12.99,
        discount: false,
    },
    {
        id: '10',
        suffix: 'pets',
        path: 'content/images/super-rat-costume.png',
        width: '262',
        height: '276',
        desc: 'super rat costume',
        price: 9.99,
        discount: false,
    },
    {
        id: '11',
        suffix: 'pets',
        path: 'content/images/witch-costume.png',
        width: '262',
        height: '276',
        desc: 'witch costume',
        price: 9.99,
        discount: false,
    },
    {
        id: '12',
        suffix: 'pets',
        path: 'content/images/dragon-costume.png',
        width: '262',
        height: '276',
        desc: 'dragon costume',
        price: 16.99,
        discount: false,
    },
    {
        id: '13',
        suffix: 'pets',
        path: 'content/images/marmaid-costume.png',
        width: '262',
        height: '276',
        desc: 'mermaid costume',
        price: 12.99,
        discount: false,
    },
    {
        id: '14',
        suffix: 'pets',
        path: 'content/images/tortilla-costume.png',
        width: '262',
        height: '276',
        desc: 'tortilla costume',
        price: 18.99,
        discount: false,
    },
    {
        id: '15',
        suffix: 'pets',
        path: 'content/images/prisioner-costume.png',
        width: '262',
        height: '276',
        desc: 'prisoner costume',
        price: 10.99,
        discount: false,
    },
]
